### ISSUE TITLE
Chart squashed in mobile view and cards are squashed for large screens(4k) 

### ISSUE THREAD

**Issue by mrshawnhum** [adrianhajdin/project_corona_tracker#16]
I seem to have a hard time adjusting the line chart to accommodate for mobile use or the cards for 4k. Any suggestions?

picture examples below:

<img width="959" alt="mobile" src="https://user-images.githubusercontent.com/63257308/87233345-16962d80-c38c-11ea-8477-216176abcf66.PNG">

<img width="960" alt="4k" src="https://user-images.githubusercontent.com/63257308/87233359-32013880-c38c-11ea-99fe-095adae83f76.PNG">

**Comment by chiragobhan** [comment]
I have fixed some front-end responsiveness in this project. Try pulling this and let me know if it helps: https://github.com/chiragobhan/react-covid-tracker

**Comment by mrshawnhum** [comment]
Your 4k resolution on your site is great! Mobile view still pretty squashed together on the numbers

**Comment by chiragobhan** [comment]
Oh. Well, at least the 4k issue is resolved. For mobile, you can fork my repo and goto "src/components/Chart/Chart.module.css". Now increase the following value (underlined in red) unless you are satisfied. Feel free to use "px" or "rem" instead of "%" if needed.
  
![Chart](https://user-images.githubusercontent.com/32812640/87358796-2a0be900-c584-11ea-89f9-8a01d654de87.PNG)

**Comment by mrshawnhum** [comment]
Looks great! Thank you! I will be sure to leave a star on your repo!
